version: '3'
services:
  bot:
    build: .
    command: python3 main.py
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/kuf_aero_bot
    environment:
      DATABASE_URL: postgres://kufpostuser:kufpasswd@postgres/kufdb
      ADMIN: <admin_tg_id>
      API_KEY: <tg_api_key>
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "kufdb"
      POSTGRES_USER: "kufpostuser"
      POSTGRES_PASSWORD: "kufpasswd"
      PGDATA: "/home/user/postgresqldata/pgdata"
    volumes:
      - .:/home/user/postgresqldata
    ports:
      - "5432:5432"


